### Basics of matrices: Gauss Elimination; Gauss-Jordan Elimination and Inverse

#### Class 25 workout 
* Date: 12/03/2026
* Vikram Khaire

In [1]:
# Next 5 cells are from last class

In [2]:
import numpy as np

In [3]:
def gauss_elimination(A):
    n = np.shape(A)[0]
    for i in range(n-1):
        for k in range(i+1, n):
            m = A[k, i]/A[i, i]
            A[k, :] = A[k, :] - m*A[i, :]
    print(A)

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
gauss_elimination(A)

[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]


In [5]:
# Example system:
A = np.array([[2, 1, -1, 1], 
              [-3, -1, 2, 1], 
              [-2, 1, 2, 1],
              [5, 2, 6, -5 ]], dtype=float)
b = np.array([[9], [-10], [-2], [5]], dtype=float)

solution = gauss_elimination(np.hstack((A,b)))

[[  2.    1.   -1.    1.    9. ]
 [  0.    0.5   0.5   2.5   3.5]
 [  0.    0.   -1.   -8.   -7. ]
 [  0.    0.    0.  -77.  -77. ]]


In [6]:
# homework -- figure out the back substitution to get (x, y, z, w)
# Also, find why dtype = float is needed?

In [7]:
# --- this clss below

In [8]:
def gauss_jorden(A):
    n = np.shape(A)[0]
    for i in range(n): #--- this line is differnt
        for k in range(n):
            if k !=i: # ---- and this
                m = A[k, i]/A[i, i]
                A[k, :] = A[k, :] - m*A[i, :]
    print(A)
    return A

In [9]:
A = np.array([[1, 2, 3], [4, 6, 6], [7, 8, 9]], dtype= float)
gauss_jorden(A)

[[ 1.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0.  6.]]


array([[ 1.,  0.,  0.],
       [ 0., -2.,  0.],
       [ 0.,  0.,  6.]])

In [10]:
# Example system:
A = np.array([[2, 1, -1, 1], 
              [-3, -1, 2, 1], 
              [-2, 1, 2, 1],
              [5, 2, 6, -5 ]], dtype=float)
b = np.array([[9], [-10], [-2], [5]], dtype=float)

gauss_jorden(np.hstack((A,b)))

[[  2.    0.    0.    0.    4. ]
 [  0.    0.5   0.    0.    1.5]
 [  0.    0.   -1.    0.    1. ]
 [  0.    0.    0.  -77.  -77. ]]


array([[  2. ,   0. ,   0. ,   0. ,   4. ],
       [  0. ,   0.5,   0. ,   0. ,   1.5],
       [  0. ,   0. ,  -1. ,   0. ,   1. ],
       [  0. ,   0. ,   0. , -77. , -77. ]])

In [11]:
# not the solution x= [x1, x2, x3, x4]is just last column divided by the diagonal element

In [12]:
# same function but normalizing the diagonal elements
def gauss_jorden_new(A):
    n = np.shape(A)[0]
    for i in range(n): 
        A[i] = A[i]/A[i,i] # normalizing the entire row by diagonal element
        for k in range(n):
            if k !=i:
                m = A[k, i] #/A[i, i] this is one
                A[k, :] = A[k, :] - m*A[i, :]
    #print(A)
    return A

In [13]:
# Example system:
A = np.array([[2, 1, -1, 1], 
              [-3, -1, 2, 1], 
              [-2, 1, 2, 1],
              [5, 2, 6, -5 ]], dtype=float)
b = np.array([[9], [-10], [-2], [5]], dtype=float)

result = gauss_jorden_new(np.hstack((A,b)))
print(result)

[[ 1.  0.  0.  0.  2.]
 [ 0.  1.  0.  0.  3.]
 [ 0.  0.  1.  0. -1.]
 [-0. -0. -0.  1.  1.]]


In [14]:
# now the solution is just the last clumnn
print(result[:, -1], '--> solution')

[ 2.  3. -1.  1.] --> solution


In [15]:
# this is nothing but calculating inverse; how let's see 

In [16]:
# first calculate the inverse of the matrix A using a numpy function
np.linalg.inv(A)

array([[ 0.41558442,  0.27272727, -0.2987013 ,  0.07792208],
       [-0.20779221, -0.63636364,  0.64935065, -0.03896104],
       [ 0.22077922,  0.36363636, -0.06493506,  0.1038961 ],
       [ 0.5974026 ,  0.45454545, -0.11688312, -0.01298701]])

In [17]:
# so now in order to get the inverse you just have to create an agumented matrix of A and I (where I is identity matrix)

In [18]:
# how to get I
np.eye(3) # 3x3 I matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# then write the code for inverse

In [20]:
def inverse(B):
    n = np.shape(B)[0]
    A = np.hstack((B, np.eye(n))) #--- only this line is different
    for i in range(n):
        A[i] = A[i]/A[i,i]
        for k in range(n):
            if k !=i:
                m = A[k, i] #/A[i, i] this is one
                A[k, :] = A[k, :] - m*A[i, :]
    #print(A)
    return A

In [21]:
# the invers is
inverse(A)[:, 4:]

array([[ 0.41558442,  0.27272727, -0.2987013 ,  0.07792208],
       [-0.20779221, -0.63636364,  0.64935065, -0.03896104],
       [ 0.22077922,  0.36363636, -0.06493506,  0.1038961 ],
       [ 0.5974026 ,  0.45454545, -0.11688312, -0.01298701]])

In [22]:
# compare with the inverse above!

In [23]:
# the code snippet below is the one that creates problem if you don not use dtype = None

In [24]:
A = np.array([[3,2],[1,1]])   # integer
print('original A= \n', A)
print('Half of it\n', A/2)
A[0] = A[0]/2 
A[1] = A[1]/2
print(A)

original A= 
 [[3 2]
 [1 1]]
Half of it
 [[1.5 1. ]
 [0.5 0.5]]
[[1 1]
 [0 0]]
