### Basics of matrices

#### Class 23 workout
* Date: 05/03/2026
* Vikram Khaire

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(A.shape)

(3, 3)


In [5]:
# no. of rows
print(A.shape[0])

3


In [6]:
# no. of cols
print(A.shape[1])

3


In [7]:
print(A[0,0]) # first element

1


In [8]:
print(A[1, 0])

4


In [9]:
print(A[0, :]) # first row

[1 2 3]


In [10]:
print(A[2, :])

[7 8 9]


In [11]:
print(A[2])

[7 8 9]


In [12]:
print(A[:, 0]) # first col

[1 4 7]


In [13]:
for i in range(A.shape[0]):
    print(A[i, :], 'row no.:', i)

[1 2 3] row no.: 0
[4 5 6] row no.: 1
[7 8 9] row no.: 2


In [14]:
for i in range(A.shape[1]):
    print(A[:, i], 'col no.:', i)

[1 4 7] col no.: 0
[2 5 8] col no.: 1
[3 6 9] col no.: 2


In [15]:
A[1,1] = 0

In [16]:
print(A)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [17]:
A[1,1] = 5

In [18]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# basic operations

In [20]:
print(2*A)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [21]:
print(A**2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [22]:
print(A-1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
# new matrics
B = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])

In [24]:
print(B)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


In [25]:
print(A+B)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]


In [26]:
print(A-B)

[[0.9 1.8 2.7]
 [3.6 4.5 5.4]
 [6.3 7.2 8.1]]


In [27]:
print(A*B)

[[0.1 0.4 0.9]
 [1.6 2.5 3.6]
 [4.9 6.4 8.1]]


In [28]:
print(A**B)

[[1.         1.14869835 1.39038917]
 [1.74110113 2.23606798 2.93015605]
 [3.90452878 5.27803164 7.22467406]]


In [29]:
9**0.9

7.224674055842076

In [30]:
# matrix multiplication
print(np.matmul(A, B))

[[ 3.   3.6  4.2]
 [ 6.6  8.1  9.6]
 [10.2 12.6 15. ]]


In [31]:
# slicing matrix
A[1:, 1:]

array([[5, 6],
       [8, 9]])

In [32]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# matrix multiplication
print(np.dot(A, B))

[[ 3.   3.6  4.2]
 [ 6.6  8.1  9.6]
 [10.2 12.6 15. ]]


In [34]:
# matrix multiplication
print(A@B)

[[ 3.   3.6  4.2]
 [ 6.6  8.1  9.6]
 [10.2 12.6 15. ]]


In [35]:
# determinant
print(np.linalg.det(A))

-9.51619735392994e-16


In [36]:
print(np.linalg.det(B))

4.448822262962232e-18
