In [1]:
import numpy as np

In [2]:
def gauss_elimination(A):
    n = np.shape(A)[0]
    for i in range(n-1):
        for k in range(i+1, n):
            m = A[k, i]/A[i, i]
            A[k, :] = A[k, :] - m*A[i, :]
    print(A)

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
gauss_elimination(A)

[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]


In [4]:
# Example system:
A = np.array([[2, 1, -1, 1], 
              [-3, -1, 2, 1], 
              [-2, 1, 2, 1],
              [5, 2, 6, -5 ]], dtype=float)
b = np.array([[9], [-10], [-2], [5]], dtype=float)

solution = gauss_elimination(np.hstack((A,b)))

[[  2.    1.   -1.    1.    9. ]
 [  0.    0.5   0.5   2.5   3.5]
 [  0.    0.   -1.   -8.   -7. ]
 [  0.    0.    0.  -77.  -77. ]]


In [5]:
# homework -- figure out the back substitution to get (x, y, z, w)
# Also find why dtype = float is needed?