### Eigenvalues and diagonalization

### Class 28 workout
* Date: 17/03/2026
* Vikram Khaire

In [1]:
import numpy as np

In [2]:
A = np.array([[2, 1, 3], [1, 2, 4], [-1, 3, -2]])
eigvalue, eigvector = np.linalg.eig(A)
print(eigvalue)

[-3.51690942  1.27299125  4.24391817]


In [3]:
print(eigvector[:, 2])

[0.64730231 0.72233115 0.24338742]


In [4]:
#A = np.array([[2, 1], [1, 2]])
max_iter = 35

u = np.array([[7], [11], [17]])

for i in range(max_iter):
    v = A@u
    norm = np.sqrt(np.sum(v**2))
    u = v/norm

    lam = u.T@A@u/(u.T@u)

    print('eigenvalue = ', lam[0,0], 'eigenvector=', u[0,0], u[1,0], u[2,0])

eigenvalue =  2.514132074234376 eigenvector= 0.6154501899615381 0.7855087950824895 -0.06478423052226717
eigenvalue =  4.380950009338232 eigenvector= 0.5613958377862122 0.5938320417471933 0.5763663934605111
eigenvalue =  3.0700268109481885 eigenvector= 0.6475284626555587 0.7619360983456068 0.012659861326357779
eigenvalue =  4.577991362783108 eigenvector= 0.6065886796866113 0.6433804281635747 0.4670244087112676
eigenvalue =  3.472898150474544 eigenvector= 0.6526712374786904 0.7536115568070264 0.07803766536054856
eigenvalue =  4.573858482945832 eigenvector= 0.6246093625432069 0.6733612409524485 0.39553480682026865
eigenvalue =  3.7400272226026736 eigenvector= 0.6531627657328294 0.7464964134131706 0.1269704935074045
eigenvalue =  4.513608765656341 eigenvector= 0.6338572921809846 0.6912347292215721 0.34701510380236983
eigenvalue =  3.9128644005014506 eigenvector= 0.652387638447789 0.7403280275834062 0.16218748649319453
eigenvalue =  4.447845037722936 eigenvector= 0.6390203917551255 0.702155

In [5]:
eigvalue, eigvector = np.linalg.eig(A)

In [6]:
print(eigvalue[0])

-3.5169094166120014


In [7]:
print(eigvector[:, 0])

[-0.33692888 -0.51187768  0.79022792]


In [8]:
#np.linalg.eig?

In [9]:
A = np.array([[2, 1, 3], [1, 2, 4], [-1, 3, -2]])
eigvalue, eigvector = np.linalg.eig(A)
print(A)

[[ 2  1  3]
 [ 1  2  4]
 [-1  3 -2]]


In [10]:
D = np.diag(eigvalue)

In [11]:
D

array([[-3.51690942,  0.        ,  0.        ],
       [ 0.        ,  1.27299125,  0.        ],
       [ 0.        ,  0.        ,  4.24391817]])

In [12]:
S = eigvector
print(S)

[[-0.33692888 -0.96685613  0.64730231]
 [-0.51187768 -0.04888301  0.72233115]
 [ 0.79022792  0.25059863  0.24338742]]


In [13]:
S_inv = np.linalg.inv(S)
print(S_inv)

[[ 0.28993131 -0.59745917  1.0020656 ]
 [-1.045113    0.89201076  0.13220446]
 [ 0.13473197  1.02138494  0.71905742]]


In [14]:
S_inv@A@S

array([[-3.51690942e+00,  9.99200722e-16, -4.55191440e-15],
       [ 1.38777878e-15,  1.27299125e+00,  1.79023463e-15],
       [ 4.44089210e-16,  3.33066907e-16,  4.24391817e+00]])

In [15]:
D

array([[-3.51690942,  0.        ,  0.        ],
       [ 0.        ,  1.27299125,  0.        ],
       [ 0.        ,  0.        ,  4.24391817]])

In [16]:
S@D@S_inv

array([[ 2.,  1.,  3.],
       [ 1.,  2.,  4.],
       [-1.,  3., -2.]])

In [17]:
# homework: read about why you are doing the above procedure for diagonalizing the matrix 
# and how it is important for physics or data science rproblms